# Generated by litai init --convert from .literate/harness-inventory.json
# evidence. Framework-owned: litai update reconciles this file.
LITAI_LEGACY := components/legacy-project-wrapper/implementation

build:
	cd $(LITAI_LEGACY) && make -f Makefile
test:
	cd $(LITAI_LEGACY) && make -f Makefile test
run:
	$(error no run command was detected during conversion; record one in .literate/harness-inventory.json and regenerate)
package:
	$(error no package command was detected during conversion; record one in .literate/harness-inventory.json and regenerate)

.PHONY: build test run package
